## !!!WARNING!!!
## Be careful changing this configuration file!
## Some changes may result in incorrect function of the program.
## Always make backups of configuration files before any changes.
## --------------------------------------------------------------

#Do not remove this label!
#_TYPE_=6
#======

#begin_hostname (do not remove this label!)
	$SERVER["socket"] == "0.0.0.0:8080" {
#end_hostname (do not remove this label!)
		#begin_docroot (do not remove this label!)
			server.document-root = "/storage/emulated/0/htdocs"
		#end_docroot (do not remove this label!)
		
		ssl.engine = "enable"
		
		#Path to the PEM file for SSL support (Should contain both the private key and the certificate)
		#Do not remove this option from this host!
		ssl.pemfile = "path_to_the_PEM_file"
		
		#Path to the CA file for support of chained certificates
		#ssl.ca-file = "path_to_the_CA_file"
	}