## !!!WARNING!!!
## Be careful changing this configuration file!
## Some changes may result in incorrect function of the program.
## Always make backups of configuration files before any changes.
## --------------------------------------------------------------

#Do not remove this label!
#_TYPE_=7
#======

server {

#begin_port (do not remove this label!)
listen 8080 ssl;
#end_port (do not remove this label!)

#begin_hostname (do not remove this label!)
server_name localhost;
#end_hostname (do not remove this label!)
	
#begin_docroot (do not remove this label!)
root /storage/emulated/0/htdocs;
#end_docroot (do not remove this label!)
	
	#Path to your certificate in PEM format. It may contain private key in PEM format.
	#Do not remove this option from this host!
	ssl_certificate path_to_your_certificate;
	
	#Path to your private key in PEM format. If your certificate includes private key then this field should contain path to the certificate.
	#Do not remove this option from this host!
	ssl_certificate_key path_to_your_private_key;

	ssl_session_timeout 5m;
	ssl_protocols SSLv2 SSLv3 TLSv1;
	ssl_ciphers HIGH:!aNULL:!MD5;
	ssl_prefer_server_ciphers on;

	index  index.html index.htm index.php;

	location @rewrite {
		rewrite	^/(.*)$ /index.php?q=$1;
	}
	
	location / {
		try_files $uri $uri/ @rewrite;
	}

	error_page   500 502 503 504  /50x.html;
	location = /50x.html {
		
	}
	
	location ~* \.php$ {
		fastcgi_pass unix:/data/data/ru.kslabs.ksweb/php.sock;
		include /data/data/ru.kslabs.ksweb/components/nginx/conf/fastcgi_params;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}
