## !!!WARNING!!!
## Be careful changing this configuration file!
## Some changes may result in incorrect function of the program.
## Always make backups of configuration files before any changes.
## --------------------------------------------------------------

#Do not remove this label!
#_TYPE_=5
#======

server {

#begin_port (do not remove this label!)
listen 8080;
#end_port (do not remove this label!)

#begin_hostname (do not remove this label!)
server_name localhost;
#end_hostname (do not remove this label!)
	
#begin_docroot (do not remove this label!)
root /storage/emulated/0/htdocs;
#end_docroot (do not remove this label!)

	index  index.html index.htm index.php;

	location @rewrite {
		rewrite	^/(.*)$ /index.php?q=$1;
	}
	
	location / {
		try_files $uri $uri/ @rewrite;
	}

	error_page   500 502 503 504  /50x.html;
	location = /50x.html {
	}
	
	location ~* \.php$ {
		fastcgi_pass unix:/data/data/ru.kslabs.ksweb/php.sock;
		#fastcgi_pass  127.0.0.1:9001;
		include /data/data/ru.kslabs.ksweb/components/nginx/conf/fastcgi_params;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}
