## !!!WARNING!!!
## Be careful changing this configuration file!
## Some changes may result in incorrect function of the program.
## Always make backups of configuration files before any changes.
## --------------------------------------------------------------

#Do not remove this label!
#_TYPE_=8
#======

#begin_port (do not remove this label!)
Define port 8080
#end_port (do not remove this label!)

#begin_docroot (do not remove this label!)
Define docroot /storage/emulated/0/htdocs
#end_docroot (do not remove this label!)

#begin_hostname (do not remove this label!)
Define hostname localhost
#end_hostname (do not remove this label!)

Listen ${port}

<VirtualHost *:${port}>

    ServerAdmin admin@email
	
    DocumentRoot ${docroot}
	
    ServerName ${hostname}
	
	<Directory ${docroot}>
		Options Indexes FollowSymLinks
		AllowOverride AuthConfig FileInfo
		Require all granted
	</Directory>

	CustomLog ${docroot}/access_log common
	
	DirectoryIndex index.html, index.php
	ProxyErrorOverride on
	KeepAlive Off


	<Directory ${docroot}>
        AuthType Basic
        AuthName "Restricted Content"
        AuthUserFile /data/data/ru.kslabs.ksweb/components/etc/.pass_apache
        Require valid-user
    </Directory>

	<Location /server-status>
		SetHandler server-status
		Order allow,deny
		Allow from all 
	</Location>
	
</VirtualHost>