export const POPULAR_FONTS = [
    "Terminal",
    "Roboto",
    "Open Sans",
    "Noto Sans JP",
    "Montserrat",
    "Lato",
    "Poppins",
    "Inter",
    "Roboto Condensed",
    "Oswald",
    "Noto Sans KR",
    "Noto Sans TC",
    "Raleway",
    "Nunito Sans",
    "Nunito",
    "Ubuntu",
    "Playfair Display",
    "Rubik",
    "Merriweather",
    "Mukta",
    "Noto Sans",
    "PT Sans",
    "Kanit",
    "Work Sans",
    "Fira Sans",
    "Lora",
    "Noto Sans SC",
    "Barlow",
    "Quicksand",
    "Hind Siliguri",
    "Mulish",
    "Titillium Web",
    "Inconsolata",
    "PT Serif",
    "Karla",
    "Heebo",
    "Josefin Sans",
    "Libre Franklin",
    "Cabin",
    "Dosis",
    "Anton",
    "Arimo",
    "Hind",
    "Oxygen",
    "Dancing Script",
    "Source Sans Pro",
    "Fjalla One",
    "Signika Negative",
    "Bebas Neue",
    "Crimson Text",
    "Manrope",
    "Assistant",
    "Abel",
    "Teko",
    "Varela Round",
    "Comfortaa",
    "Bitter",
    "Asap",
    "Exo 2",
    "Pacifico",
    "Zilla Slab",
    "Archivo Narrow",
    "Cormorant Garamond",
    "Maven Pro",
    "EB Garamond",
    "Righteous",
    "Caveat",
    "Questrial",
    "Vollkorn",
    "Domine",
    "Red Hat Display",
    "Libre Baskerville",
    "Amatic SC",
    "Rokkitt",
    "Indie Flower",
    "Crete Round",
    "Chakra Petch",
    "Yanone Kaffeesatz",
    "Bree Serif",
    "Sawarabi Mincho",
    "Saira Semi Condensed",
    "Play",
    "Taviraj",
    "Alfa Slab One",
    "Noto Serif",
    "Jost",
    "Orbitron",
    "Monda",
    "Marmelad",
    "Alegreya Sans",
    "Alata",
    "Saira",
    "Prompt",
    "Concert One",
    "Ruda",
    "Cormorant",
    "Viga",
    "Slabo 27px",
    "Russo One",
    "Fredoka One",
    "Old Standard TT",
    "Public Sans",
    "Exo",
    "Tinos",
    "Signika",
    "Patua One",
    "Space Grotesk",
    "Changa",
    "Sarabun",
    "Krub",
    "Chivo",
    "News Cycle",
    "Volkhov",
    "Kumbh Sans",
    "Blinker",
    "Alegreya",
    "Philosopher",
    "Saira Condensed",
    "Lexend Deca",
    "Lexend",
    "Epilogue",
    "Gelasio",
    "Cinzel",
    "Khand",
    "Niramit",
    "Noticia Text",
    "Tiantian",
    "Pathway Gothic One",
    "Cantarell",
    "Caudex",
    "Mitr",
    "Istok Web",
    "Sanchez",
    "Francois One",
    "Kalam",
    "Prata",
    "Satisfy",
    "Cuprum",
    "Releway",
    "Actor",
    "Vidaloka",
    "Alatsi",
    "Zilla Slab Highlight",
    "Sintony",
    "Basic",
    "Gudea",
    "Julius Sans One",
    "Fira Sans Condensed",
    "Tenor Sans",
    "Alice",
    "Secular One",
    "Enriqueta",
    "Amaranth",
    "Antic Slab",
    "Arapey",
    "Bai Jamjuree",
    "Krona One",
    "Pontano Sans",
    "Gothic A1",
    "Glegoo",
    "Judson",
    "Abhaya Libre",
    "Sura",
    "Coda",
    "Spinnaker",
    "Markazi Text",
    "Overpass",
    "Be Vietnam Pro",
    "Frank Ruhl Libre",
    "Muli",
    "Courgette",
    "Yantramanav",
    "Cardo",
    "Kreon",
    "Sacramento",
    "Laila",
    "Sriracha",
    "M PLUS Rounded 1c",
    "Hind Madurai",
    "Palanquin",
    "Pridi",
    "Quattrocento Sans",
    "Arsenal",
    "Copse",
    "Suez One",
    "Cutive Mono",
    "Asap Condensed",
    "Nobile",
    "Yeseva One",
    "Adamina",
    "Gothic A1",
    "Fira Sans Extra Condensed",
    "Amiri",
    "Aleo",
    "Ovo",
    "Trocchi",
    "Average",
    "Macondo",
    "Jura",
    "Candal",
    "Scada",
    "Halant",
    "Vesper Libre",
    "Neuton",
    "Cambo",
    "Alike",
    "Sorts Mill Goudy",
    "Rufina",
    "Tauri",
    "Orienta",
    "Donegal One",
    "Habibi",
    "Nixie One",
    "Palanquin Dark",
    "Jolly Lodger",
    "Share Tech Mono"
];
